[package]
name = "cryptopals_one"
version = "0.1.0"
edition = "2024"

[dependencies]
crypto-bigint = "0.6.1"
base64ct = {version = "1.8.0", features = ["alloc"]}
hex = "0.4.3"
rust_decimal = "1.39.0"
